/**
 * TypeScript Type Definitions
 * 
 * =============================================================================
 * APPLICATION DATA MODELS
 * =============================================================================
 * 
 * This file defines TypeScript interfaces for all core data structures
 * in the AI Learning Tutor application.
 * 
 * Type Safety Benefits:
 * 
 * 1. Compile-time Error Detection:
 *    - Catch typos and type mismatches before runtime
 *    - IDE autocompletion for better developer experience
 * 
 * 2. Documentation:
 *    - Interfaces serve as living documentation
 *    - Property purposes are clearly defined
 * 
 * 3. Refactoring Safety:
 *    - Changes to types are caught across the codebase
 *    - Reduces bugs from inconsistent data shapes
 * 
 * Security Note:
 * 
 * While TypeScript provides type safety, it does NOT provide
 * runtime validation. All external data (API responses, user input)
 * should be validated at runtime using a library like Zod.
 * 
 * These types are for internal use and assume data has been validated.
 * 
 * @module types
 */

'use strict';

// =============================================================================
// LESSON TYPES
// =============================================================================

/**
 * Represents a single lesson within a module.
 * 
 * Lessons are the atomic unit of learning content. Each lesson
 * contains educational material generated by AI and may include
 * Markdown-formatted content.
 */
export interface Lesson {
  /** 
   * Unique identifier for the lesson.
   * Format: "l-{moduleIndex}-{lessonIndex}" (e.g., "l-0-1")
   * 
   * @security This is a client-generated ID, not tied to any
   * database or authentication system. Safe to expose.
   */
  id: string;
  
  /** 
   * Display title of the lesson.
   * Should be concise and descriptive.
   */
  title: string;
  
  /** 
   * Brief description of what the lesson covers.
   * Used as a preview in course navigation.
   */
  description: string;
  
  /** 
   * Whether the user has completed this lesson.
   * Used for progress tracking and unlocking next lessons.
   * 
   * @default false
   */
  isCompleted: boolean;
  
  /** 
   * Whether the lesson is locked (not yet accessible).
   * Lessons are unlocked sequentially after completing quizzes.
   * 
   * @default true (first lesson only is false)
   */
  isLocked: boolean;
  
  /** 
   * Markdown content for the lesson.
   * Generated by AI when the lesson is first accessed.
   * 
   * @optional Content may not be loaded until user opens the lesson
   * @security Content is generated server-side and stored client-side.
   * No sensitive user data is included in the content.
   */
  content?: string;
}

// =============================================================================
// MODULE TYPES
// =============================================================================

/**
 * Represents a module within a course.
 * 
 * Modules group related lessons together and form the high-level
 * structure of a course. Each module typically covers a distinct
 * aspect of the overall topic.
 */
export interface Module {
  /** 
   * Unique identifier for the module.
   * Format: "m-{index}" (e.g., "m-0")
   */
  id: string;
  
  /** 
   * Display title of the module.
   */
  title: string;
  
  /** 
   * Brief description of what the module covers.
   */
  description: string;
  
  /** 
   * Ordered array of lessons within this module.
   * Lessons are processed sequentially (order matters for unlocking).
   */
  lessons: Lesson[];
}

// =============================================================================
// COURSE TYPES
// =============================================================================

/**
 * Represents a complete course with multiple modules.
 * 
 * Courses are the top-level organizational unit for learning content.
 * Each course is generated for a specific topic and contains
 * multiple modules with progressive difficulty.
 */
export interface Course {
  /** 
   * Unique identifier for the course.
   * Generated using crypto.randomUUID() - a cryptographically
   * secure random identifier.
   * 
   * @security This ID is client-generated and doesn't expose
   * any sensitive information. It's used for localStorage keys
   * and course identification.
   */
  id: string;
  
  /** 
   * Display title of the course.
   * Based on the user's requested topic.
   */
  title: string;
  
  /** 
   * Description of what learners will achieve.
   * Generated by AI to match the course content.
   */
  description: string;
  
  /** 
   * Ordered array of modules within this course.
   * Modules are designed to build progressively.
   */
  modules: Module[];
  
  /** 
   * Unix timestamp (milliseconds) when the course was created.
   * Used for sorting and identifying recent courses.
   * 
   * @security Timestamp is generated client-side and could be
   * manipulated. For trust, use server-generated timestamps.
   */
  createdAt: number;
}

// =============================================================================
// QUIZ TYPES
// =============================================================================

/**
 * Represents a single quiz question with multiple choice options.
 * 
 * Questions are designed to test understanding, not just recall.
 * Each question has one correct answer and detailed explanations.
 */
export interface QuizQuestion {
  /** 
   * The question text.
   * Should be clear and specific.
   */
  question: string;
  
  /** 
   * Array of 4 answer options.
   * Options should be plausible and similar in style/length.
   */
  options: string[];
  
  /** 
   * Zero-based index of the correct answer within options array.
   * 
   * @example
   * // If correctAnswerIndex is 2, the third option is correct
   * // options[2] === correctAnswer
   * 
   * @security This is a generated value from AI content.
   * In production, consider server-side answer validation
   * to prevent cheating.
   */
  correctAnswerIndex: number;
  
  /** 
   * Explanation of why the answer is correct (and why others are wrong).
   * Used as a learning tool after the user answers.
   */
  explanation: string;
}

/**
 * Represents a complete quiz with multiple questions.
 * 
 * Quizzes are generated after lesson completion and must be
 * passed (70%+) to unlock the next lesson.
 */
export interface Quiz {
  /** 
   * Display title of the quiz.
   * Typically references the associated lesson.
   */
  title: string;
  
  /** 
   * Array of quiz questions.
   * Usually 3-5 questions per quiz.
   */
  questions: QuizQuestion[];
}

// =============================================================================
// TYPE UTILITIES
// =============================================================================

/**
 * Helper type to extract the type of a lesson's content.
 * Useful for components that need to handle lesson rendering.
 */
export type LessonContent = NonNullable<Lesson['content']>;

/**
 * Helper type to get the shape of a completed lesson.
 * Useful for type narrowing in handlers.
 */
export type CompletedLesson = Omit<Lesson, 'isCompleted' | 'isLocked'> & {
  isCompleted: true;
  isLocked: false;
  content: string;
};

/**
 * Helper type for course progress statistics.
 */
export interface CourseProgress {
  totalLessons: number;
  completedLessons: number;
  percentComplete: number;
  currentModuleIndex: number;
  currentLessonIndex: number;
}

// =============================================================================
// SERIALIZATION
// =============================================================================

/**
 * Type guard to check if an object is a valid Course.
 * 
 * @param value - Unknown value to check
 * @returns True if the value is a valid Course object
 * 
 * @security This only validates structure, not content.
 * For security, also validate data from external sources.
 * 
 * @example
 * const parsed = JSON.parse(localStorage.getItem('course'));
 * if (isValidCourse(parsed)) {
 *   // TypeScript now knows parsed is Course
 * }
 */
export function isValidCourse(value: unknown): value is Course {
  if (typeof value !== 'object' || value === null) return false;
  
  const course = value as Record<string, unknown>;
  
  return (
    typeof course.id === 'string' &&
    typeof course.title === 'string' &&
    typeof course.description === 'string' &&
    typeof course.createdAt === 'number' &&
    Array.isArray(course.modules)
  );
}

/**
 * Type guard to check if an object is a valid Quiz.
 */
export function isValidQuiz(value: unknown): value is Quiz {
  if (typeof value !== 'object' || value === null) return false;
  
  const quiz = value as Record<string, unknown>;
  
  return (
    typeof quiz.title === 'string' &&
    Array.isArray(quiz.questions)
  );
}
